version: '3.8'

services:
  mova-api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    container_name: mova-api
    ports:
      - "8080:8080"
    environment:
      - MOVA_PORT=8080
      - MOVA_HOST=0.0.0.0
      - MOVA_LOG_LEVEL=info
      - MOVA_STATE_DIR=/app/state
    volumes:
      - mova_state:/app/state
      - mova_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mova-network

  mova-console:
    build:
      context: ../../mova-console
      dockerfile: Dockerfile
    container_name: mova-console
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://mova-api:8080
    depends_on:
      mova-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mova-network

volumes:
  mova_state:
    driver: local
  mova_logs:
    driver: local

networks:
  mova-network:
    driver: bridge